### PR TITLE
Align files

### PR DESCRIPTION
**Pull request by architectbot**
This PR is generated by https://github.com/giantswarm/github

### CODE REVIEW

**Comment by ubergesundheit** [comment]
@pipo02mix can you take a look at the failing gitleaks workflow?

**Comment by pipo02mix** [comment]
It is weird, does not fail in my local. I will check the gitleaks version but those files were created statically by upstream

``` gitleaks --verbose --redact                                                                      (current-context is not set)
INFO[0000] opening .
INFO[0000] scan time: 28 milliseconds 812 microseconds
INFO[0000] No leaks found```

**Comment by ubergesundheit** [comment]
Seems this is resolved through updating the gitleaks action.. merging.. :)

**Comment by pipo02mix** [comment]
how did you update the action? in common gs github repo?

**Comment by ubergesundheit** [comment]
Devctl was updated several times today :)

**Pull request merged**
